In [57]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
import pandas as pd

In [60]:
List_Test = [
                    [
                    "Nose_X_1", "Nose_Y_1", "Nose_X_2", "Nose_Y_2", "Nose_X_3", "Nose_Y_3",
                    "Neck_X_1", "Neck_Y_1", "Neck_X_2", "Neck_Y_2", "Neck_X_3", "Neck_Y_3",
                    "RShoulder_X_1", "RShoulder_Y_1", "RShoulder_X_2", "RShoulder_Y_2", "RShoulder_X_3", "RShoulder_Y_3",
                    "RElbow_X_1", "RElbow_Y_1", "RElbow_X_2", "RElbow_Y_2", "RElbow_X_3", "RElbow_Y_3",
                    "RWrist_X_1", "RWrist_Y_1", "RWrist_X_2", "RWrist_Y_2", "RWrist_X_3", "RWrist_Y_3",
                    "LShoulder_X_1", "LShoulder_Y_1", "LShoulder_X_2", "LShoulder_Y_2", "LShoulder_X_3", "LShoulder_Y_3",
                    "LElbow_X_1", "LElbow_Y_1", "LElbow_X_2", "LElbow_Y_2", "LElbow_X_3", "LElbow_Y_3",
                    "LWrist_X_1", "LWrist_Y_1", "LWrist_X_2", "LWrist_Y_2", "LWrist_X_3", "LWrist_Y_3",
                    "RHip_X_1", "RHip_Y_1", "RHip_X_2", "RHip_Y_2", "RHip_X_3", "RHip_Y_3",
                    "RKnee_X_1", "RKnee_Y_1", "RKnee_X_2", "RKnee_Y_2", "RKnee_X_3", "RKnee_Y_3",
                    "RAnkle_X_1", "RAnkle_Y_1", "RAnkle_X_2", "RAnkle_Y_2", "RAnkle_X_3", "RAnkle_Y_3",
                    "LHip_X_1", "LHip_Y_1", "LHip_X_2", "LHip_Y_2", "LHip_X_3", "LHip_Y_3",
                    "LKnee_X_1", "LKnee_Y_1", "LKnee_X_2", "LKnee_Y_2", "LKnee_X_3", "LKnee_Y_3",
                    "LAnkle_X_1", "LAnkle_Y_1", "LAnkle_X_2", "LAnkle_Y_2", "LAnkle_X_3", "LAnkle_Y_3",
                    "REye_X_1", "REye_Y_1", "REye_X_2", "REye_Y_2", "REye_X_3", "REye_Y_3",
                    "LEye_X_1", "LEye_Y_1", "LEye_X_2", "LEye_Y_2", "LEye_X_3", "LEye_Y_3",
                    "REar_X_1", "REar_Y_1", "REar_X_2", "REar_Y_2", "REar_X_3", "REar_Y_3",
                    "LEar_X_1", "LEar_Y_1", "LEar_X_2", "LEar_Y_2", "LEar_X_3", "LEar_Y_3",
                    "Background_X_1", "Background_Y_1", "Background_X_2", "Background_Y_2", "Background_X_3", "Background_Y_3"
                    ],

                    [
                    "2_Nose_X_1", "2_Nose_Y_1", "2_Nose_X_2", "2_Nose_Y_2", "2_Nose_X_3", "2_Nose_Y_3",
                    "Neck_X_1", "2_Neck_Y_1", "2_Neck_X_2", "2_Neck_Y_2", "2_Neck_X_3", "2_Neck_Y_3",
                    "RShoulder_X_1", "2_RShoulder_Y_1", "2_RShoulder_X_2", "2_RShoulder_Y_2", "2_RShoulder_X_3", "2_RShoulder_Y_3",
                    "RElbow_X_1", "2_RElbow_Y_1", "2_RElbow_X_2", "2_RElbow_Y_2", "2_RElbow_X_3", "2_RElbow_Y_3",
                    "RWrist_X_1", "2_RWrist_Y_1", "2_RWrist_X_2", "2_RWrist_Y_2", "2_RWrist_X_3", "2_RWrist_Y_3",
                    "LShoulder_X_1", "2_LShoulder_Y_1", "2_LShoulder_X_2", "2_LShoulder_Y_2", "2_LShoulder_X_3", "2_LShoulder_Y_3",
                    "LElbow_X_1", "2_LElbow_Y_1", "2_LElbow_X_2", "2_LElbow_Y_2", "2_LElbow_X_3", "2_LElbow_Y_3",
                    "LWrist_X_1", "2_LWrist_Y_1", "2_LWrist_X_2", "2_LWrist_Y_2", "2_LWrist_X_3", "2_LWrist_Y_3",
                    "RHip_X_1", "2_RHip_Y_1", "2_RHip_X_2", "2_RHip_Y_2", "2_RHip_X_3", "2_RHip_Y_3",
                    "RKnee_X_1", "2_RKnee_Y_1", "2_RKnee_X_2", "2_RKnee_Y_2", "2_RKnee_X_3", "2_RKnee_Y_3",
                    "RAnkle_X_1", "2_RAnkle_Y_1", "2_RAnkle_X_2", "2_RAnkle_Y_2", "2_RAnkle_X_3", "2_RAnkle_Y_3",
                    "LHip_X_1", "2_LHip_Y_1", "2_LHip_X_2", "2_LHip_Y_2", "2_LHip_X_3", "2_LHip_Y_3",
                    "LKnee_X_1", "2_LKnee_Y_1", "2_LKnee_X_2", "2_LKnee_Y_2", "2_LKnee_X_3", "2_LKnee_Y_3",
                    "LAnkle_X_1", "2_LAnkle_Y_1", "2_LAnkle_X_2", "2_LAnkle_Y_2", "2_LAnkle_X_3", "2_LAnkle_Y_3",
                    "REye_X_1", "2_REye_Y_1", "2_REye_X_2", "2_REye_Y_2", "2_REye_X_3", "2_REye_Y_3",
                    "LEye_X_1", "2_LEye_Y_1", "2_LEye_X_2", "2_LEye_Y_2", "2_LEye_X_3", "2_LEye_Y_3",
                    "REar_X_1", "2_REar_Y_1", "2_REar_X_2", "2_REar_Y_2", "2_REar_X_3", "2_REar_Y_3",
                    "LEar_X_1", "2_LEar_Y_1", "2_LEar_X_2", "2_LEar_Y_2", "2_LEar_X_3", "2_LEar_Y_3",
                    "Background_X_1", "2_Background_Y_1", "2_Background_X_2", "2_Background_Y_2", "2_Background_X_3", "2_Background_Y_3"
                    ]
            ]

List_Test = np.reshape(List_Test,(2,19,3,2)).swapaxes(2,3)

print(List_Test.shape)
print()
print(List_Test[0])
print()
print(List_Test[1])
print()
print(List_Test[2])
print()
print(List_Test[3])

(2, 19, 2, 3)

[[['Nose_X_1' 'Nose_X_2' 'Nose_X_3']
  ['Nose_Y_1' 'Nose_Y_2' 'Nose_Y_3']]

 [['Neck_X_1' 'Neck_X_2' 'Neck_X_3']
  ['Neck_Y_1' 'Neck_Y_2' 'Neck_Y_3']]

 [['RShoulder_X_1' 'RShoulder_X_2' 'RShoulder_X_3']
  ['RShoulder_Y_1' 'RShoulder_Y_2' 'RShoulder_Y_3']]

 [['RElbow_X_1' 'RElbow_X_2' 'RElbow_X_3']
  ['RElbow_Y_1' 'RElbow_Y_2' 'RElbow_Y_3']]

 [['RWrist_X_1' 'RWrist_X_2' 'RWrist_X_3']
  ['RWrist_Y_1' 'RWrist_Y_2' 'RWrist_Y_3']]

 [['LShoulder_X_1' 'LShoulder_X_2' 'LShoulder_X_3']
  ['LShoulder_Y_1' 'LShoulder_Y_2' 'LShoulder_Y_3']]

 [['LElbow_X_1' 'LElbow_X_2' 'LElbow_X_3']
  ['LElbow_Y_1' 'LElbow_Y_2' 'LElbow_Y_3']]

 [['LWrist_X_1' 'LWrist_X_2' 'LWrist_X_3']
  ['LWrist_Y_1' 'LWrist_Y_2' 'LWrist_Y_3']]

 [['RHip_X_1' 'RHip_X_2' 'RHip_X_3']
  ['RHip_Y_1' 'RHip_Y_2' 'RHip_Y_3']]

 [['RKnee_X_1' 'RKnee_X_2' 'RKnee_X_3']
  ['RKnee_Y_1' 'RKnee_Y_2' 'RKnee_Y_3']]

 [['RAnkle_X_1' 'RAnkle_X_2' 'RAnkle_X_3']
  ['RAnkle_Y_1' 'RAnkle_Y_2' 'RAnkle_Y_3']]

 [['LHip_X_1' 'LHip_X_2

IndexError: index 2 is out of bounds for axis 0 with size 2

In [62]:
train = pd.read_csv("Media/train.csv").values
test = pd.read_csv("Media/test.csv").values

trainX = np.reshape(train[:, 1:],(train.shape[0],19,3,2)).swapaxes(2,3)
testX = np.reshape(test[:, 1:],(test.shape[0],19,3,2)).swapaxes(2,3)

y_train = train[:,0]
y_test = test[:,0]

non-violent: [[[632 632 632]
  [164 164 164]]

 [[608 608 608]
  [211 211 211]]

 [[585 585 585]
  [211 211 211]]

 [[538 538 538]
  [234 234 234]]

 [[585 585 585]
  [281 281 281]]

 [[655 655 655]
  [211 211 211]]

 [[655 655 655]
  [258 258 258]]

 [[632 632 632]
  [281 281 281]]

 [[585 585 585]
  [305 305 305]]

 [[608 608 608]
  [399 399 399]]

 [[608 608 608]
  [469 469 469]]

 [[632 632 632]
  [305 305 305]]

 [[679 679 679]
  [375 375 375]]

 [[679 679 679]
  [469 469 469]]

 [[632 632 632]
  [164 164 164]]

 [[632 632 632]
  [164 164 164]]

 [[608 608 608]
  [164 164 164]]

 [[655 655 655]
  [164 164 164]]

 [[23 23 23]
  [0 0 0]]]
non-violent: [[[632 632 632]
  [164 164 164]]

 [[608 608 608]
  [211 211 211]]

 [[585 585 585]
  [211 211 211]]

 [[538 538 538]
  [234 234 234]]

 [[585 585 585]
  [281 281 281]]

 [[655 655 655]
  [211 211 211]]

 [[655 655 655]
  [258 258 258]]

 [[632 632 632]
  [281 281 281]]

 [[585 585 585]
  [305 305 305]]

 [[608 608 608]
  [399 399 399]